excluded:
  - Carthage
  - Pods

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

disabled_rules:
  - trailing_whitespace
  - cyclomatic_complexity
  - function_body_length
  - type_name
  - shorthand_operator
  - multiple_closures_with_trailing_closure
  - identifier_name
  
# Custom rules
identifier_name:
  min_length: 1
force_cast: warning
force_try:
  severity: warning
number_separator:
  minimum_length: 5