language: swift
xcode_workspace: PhotoMemories.xcworkspace # path to your xcodeproj folder
xcode_scheme: PhotoMemories
before_install:
   - rvm use system
   - sudo gem install cocoapods -v '1.3.1'

script:
    xctool -workspace ProjectName.xcworkspace -scheme ProjectName build -sdk iphonesimulator
