language: swift
xcode_workspace: PhotoMemories.xcworkspace # path to your xcodeproj folder
xcode_scheme: PhotoMemories
xcode_sdk: iphonesimulator11.3
osx_image: xcode9.4
#before_install:
#   - rvm use system
#   - sudo gem install cocoapods -v '1.3.1'

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace PhotoMemories.xcworkspace -scheme PhotoMemories CODE_SIGNING_REQUIRED=NO
