language: objective-c
xcode_workspace: PhotoMemories.xcworkspace
xcode_scheme: PhotoMemories
xcode_sdk: iphonesimulator11.3
osx_image: xcode9.4

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace PhotoMemories.xcworkspace -scheme PhotoMemories CODE_SIGNING_REQUIRED=NO
# - fastlane tests
# - fastlane beta